services:
  rabbit-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/.data/rabbitnode.sqlite
      - NUXT_OPENAI_API_KEY=${OPENAI_KEY}
    volumes:
      - rabbit_app_data:/app/.data

volumes:
  rabbit_app_data:
